//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Input) DeepCopyInto(out *Input) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Input.
func (in *Input) DeepCopy() *Input {
	if in == nil {
		return nil
	}
	out := new(Input)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Input) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InputSpec) DeepCopyInto(out *InputSpec) {
	*out = *in
	if in.ExtraResources != nil {
		in, out := &in.ExtraResources, &out.ExtraResources
		*out = make([]ResourceSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(Policy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InputSpec.
func (in *InputSpec) DeepCopy() *InputSpec {
	if in == nil {
		return nil
	}
	out := new(InputSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PatchPolicy) DeepCopyInto(out *PatchPolicy) {
	*out = *in
	if in.FromFieldPath != nil {
		in, out := &in.FromFieldPath, &out.FromFieldPath
		*out = new(FromFieldPathPolicy)
		**out = **in
	}
	if in.MergeOptions != nil {
		in, out := &in.MergeOptions, &out.MergeOptions
		*out = new(v1.MergeOptions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PatchPolicy.
func (in *PatchPolicy) DeepCopy() *PatchPolicy {
	if in == nil {
		return nil
	}
	out := new(PatchPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Policy) DeepCopyInto(out *Policy) {
	*out = *in
	if in.Resolution != nil {
		in, out := &in.Resolution, &out.Resolution
		*out = new(v1.ResolutionPolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Policy.
func (in *Policy) DeepCopy() *Policy {
	if in == nil {
		return nil
	}
	out := new(Policy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSource) DeepCopyInto(out *ResourceSource) {
	*out = *in
	if in.Ref != nil {
		in, out := &in.Ref, &out.Ref
		*out = new(ResourceSourceReference)
		**out = **in
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(ResourceSourceSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSource.
func (in *ResourceSource) DeepCopy() *ResourceSource {
	if in == nil {
		return nil
	}
	out := new(ResourceSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSourceReference) DeepCopyInto(out *ResourceSourceReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSourceReference.
func (in *ResourceSourceReference) DeepCopy() *ResourceSourceReference {
	if in == nil {
		return nil
	}
	out := new(ResourceSourceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSourceSelector) DeepCopyInto(out *ResourceSourceSelector) {
	*out = *in
	if in.MaxMatch != nil {
		in, out := &in.MaxMatch, &out.MaxMatch
		*out = new(uint64)
		**out = **in
	}
	if in.MinMatch != nil {
		in, out := &in.MinMatch, &out.MinMatch
		*out = new(uint64)
		**out = **in
	}
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make([]ResourceSourceSelectorLabelMatcher, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSourceSelector.
func (in *ResourceSourceSelector) DeepCopy() *ResourceSourceSelector {
	if in == nil {
		return nil
	}
	out := new(ResourceSourceSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSourceSelectorLabelMatcher) DeepCopyInto(out *ResourceSourceSelectorLabelMatcher) {
	*out = *in
	in.ValueSelectorWithPolicy.DeepCopyInto(&out.ValueSelectorWithPolicy)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSourceSelectorLabelMatcher.
func (in *ResourceSourceSelectorLabelMatcher) DeepCopy() *ResourceSourceSelectorLabelMatcher {
	if in == nil {
		return nil
	}
	out := new(ResourceSourceSelectorLabelMatcher)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValueFromCompositeFieldPath) DeepCopyInto(out *ValueFromCompositeFieldPath) {
	*out = *in
	if in.ValueFromFieldPath != nil {
		in, out := &in.ValueFromFieldPath, &out.ValueFromFieldPath
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValueFromCompositeFieldPath.
func (in *ValueFromCompositeFieldPath) DeepCopy() *ValueFromCompositeFieldPath {
	if in == nil {
		return nil
	}
	out := new(ValueFromCompositeFieldPath)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValueFromCompositeFieldPathWithPolicy) DeepCopyInto(out *ValueFromCompositeFieldPathWithPolicy) {
	*out = *in
	in.ValueFromCompositeFieldPath.DeepCopyInto(&out.ValueFromCompositeFieldPath)
	if in.FromFieldPathPolicy != nil {
		in, out := &in.FromFieldPathPolicy, &out.FromFieldPathPolicy
		*out = new(FromFieldPathPolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValueFromCompositeFieldPathWithPolicy.
func (in *ValueFromCompositeFieldPathWithPolicy) DeepCopy() *ValueFromCompositeFieldPathWithPolicy {
	if in == nil {
		return nil
	}
	out := new(ValueFromCompositeFieldPathWithPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValueFromValue) DeepCopyInto(out *ValueFromValue) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValueFromValue.
func (in *ValueFromValue) DeepCopy() *ValueFromValue {
	if in == nil {
		return nil
	}
	out := new(ValueFromValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValueSelector) DeepCopyInto(out *ValueSelector) {
	*out = *in
	in.ValueSelectorBase.DeepCopyInto(&out.ValueSelectorBase)
	in.ValueFromCompositeFieldPath.DeepCopyInto(&out.ValueFromCompositeFieldPath)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValueSelector.
func (in *ValueSelector) DeepCopy() *ValueSelector {
	if in == nil {
		return nil
	}
	out := new(ValueSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValueSelectorBase) DeepCopyInto(out *ValueSelectorBase) {
	*out = *in
	in.ValueFromValue.DeepCopyInto(&out.ValueFromValue)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValueSelectorBase.
func (in *ValueSelectorBase) DeepCopy() *ValueSelectorBase {
	if in == nil {
		return nil
	}
	out := new(ValueSelectorBase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValueSelectorWithPolicy) DeepCopyInto(out *ValueSelectorWithPolicy) {
	*out = *in
	in.ValueSelectorBase.DeepCopyInto(&out.ValueSelectorBase)
	in.ValueFromCompositeFieldPathWithPolicy.DeepCopyInto(&out.ValueFromCompositeFieldPathWithPolicy)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValueSelectorWithPolicy.
func (in *ValueSelectorWithPolicy) DeepCopy() *ValueSelectorWithPolicy {
	if in == nil {
		return nil
	}
	out := new(ValueSelectorWithPolicy)
	in.DeepCopyInto(out)
	return out
}
